package Aca::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

# use Aca;

# my $name = Aca->config->{database};
my $name = "aca022";

__PACKAGE__->config(
    schema_class => 'Aca::Schema',
    
    connect_info => {
        dsn => "dbi:Pg:dbname=$name",
        user => '',
        password => '',
    }
);

=head1 NAME

Aca::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Aca>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Aca::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Dr Bean

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
