# Proper nouns.  Note that our Proper tag is just for people.
2	Proper	PersonName
2	Proper	PlaceName

1	PersonName	Arthur
1	PersonName	Guinevere
1	PersonName	Sir Lancelot
1	PersonName	Sir Bedevere
1	PersonName	Zoot
1	PersonName	Dingo
1	PersonName	Patsy
1	PersonName	Uther Pendragon


# More proper nouns, not people.

1	PlaceName	Camelot
1	PlaceName	England
1	PlaceName	Holy Grail
1	PlaceName	the Holy Grail
1	PlaceName	Round Table
1	PlaceName	the Round Table

