1	S1	Statement .
1	S1	Statement !
1	S1	Command !
1	S1	Question ?

1	Statement	either Statement or Statement
1	Statement	neither Statement nor Statement
1	Statement	Statement CoCon VP
1	Statement	Statement SubCon Statement
1	Statement	SubCon Statement , Statement
1	Statement	WhAdv Statement , Statement
1	Statement	NP VP
1	Statement	it is NP who VP

1	Command	do not VerbBase
1	Command	VerbBase 

1	Question	Aux NP VP
1	Question	WhPron Aux NP VP
1	Question	WhPron VP
1	Question	WhAdv Aux NP VP
