module Tests where

import LogicalForm
import Parsing

michelle_test = [
	"Some people annoyed Michelle.",
	"Michelle had throat cancer.",
	"Michelle was in the gym.",
	"The woman said to Michelle, What's that funny sound.",
	"Michelle turned around hands on hips.",
	"Michelle wasn't a shrinking violet.",
	"Michelle answered the phone.",
	"Michelle played a joke on telemarketers.",
	"Michelle sounded like a computer.",
	"People thought Michelle was a computer.",
	"Michelle went to a restaurant.",
	"The woman at the front desk greeted Michelle.",
	"Michelle felt like a movie star.",
	"Michelle was scared on the night before the operation.",
	"Renee slept in the bed with Michelle.",
	"Renee slept with Michelle on the night before the operation.",
	"Renee slept in the bed with Michelle on the night before the operation.",
	"Michelle was scared.",
	"Michelle asked Renee to stay.",
	"Michelle asked Renee to stay with her.",
	"Renee left New York.",
	"Renee lived with Michelle for a year."
	]

renee_test = [
	"Renee's daughter was Michelle.",
	"Michelle was Renee's daughter.",
	"A woman annoyed Renee.",
	"Some people annoyed Renee.",
	"Renee had throat cancer.",
	"Renee had an electrolarynx.",
	"Renee didn't have a voice.",
	"Renee was in the gym.",
	"Amanda was a woman in the gym.",
	"The woman said, What's that sound.",
	"The woman said, What's that funny sound.",
	"The woman said to Renee, What's that funny sound.",
	"Renee turned around hands on hips.",
	"The woman that offended Renee was Amanda.",
	"Amanda was the woman that offended Renee.",
	"Michelle said, Renee wasn't a shrinking violet.",
	"Renee answered the phone.",
	"Renee played a joke on telemarketers.",
	"Renee sounded like a computer.",
	"People thought Renee was a computer.",
	"Renee went to a restaurant.",
	"People were kind",
	"People were kind to Renee.",
	"The woman at the front desk greeted Renee.",
	"Renee felt like a movie star.",
	"Renee was scared on the night before the operation.",
	"Renee was scared.",
	"Renee was a scared woman.",
	"Renee was a woman.",
	"Michelle slept in the bed with Renee.",
	"Michelle slept with Renee on the night before the operation.",
	"Michelle slept in the bed with Renee on the night before the operation.",
	"Renee asked Michelle to stay.",
	"Renee asked Michelle to stay with her.",
	"Renee lived in California.",
	"Michelle lived in New York.",
	"Michelle left New York.",
	"Michelle lived with Renee.",
	"Michelle lived with Renee in California.",
	"Michelle lived with Renee for a year.",
	"Michelle lived with Renee in California for a year.",
	"Renee lived with Michelle in California for a year."
	]

wh_test = [
	-- "Which woman annoyed Renee?",
	"Who annoyed Renee?",
	"Who did some people annoy?",
	"Who had throat cancer?",
	"Who was in the gym?",
	"Who said, What's that sound?",
	"Who said, What's that funny sound?",
	"Who said something to Renee?",
	"Who was the woman that offended Renee?",
	"Who turned around?",
	"Who wasn't a shrinking violet?",
	"Who answered the phone?",
	"Who did Renee play a joke on?",
	"Who sounded like a computer?",
	"Who thought Renee was a computer?",
	"Who went to a restaurant?",
	"Who was kind?",
	"Who were kind to Renee?",
	"Who at the front desk greeted Renee?",
	"Who felt like a movie star?",
	"Who was scared on the night before the operation?",
	"Who was scared?",
	"Who slept in the bed with Renee?",
	"Who slept with Renee on the night before the operation?",
	"Who slept in the bed with Renee on the night before the operation?",
	"Who asked Michelle to stay?",
	"Who asked Michelle to stay with her?",
	"Who left New York?",
	"Who lived with Renee for a year?",
	"Who lived with Renee in California?",
	"Who lived with Renee in California for a year?"
	]

