---
' preliminary': 初步
accommodate: 容纳
analogy: 比喻
anticipate: 预料
assure: 保证
attain: 达到
behalf: 代表
bulk: 体积
cease: 停止
coherent: 连贯
coincide: 重合
commence: 开始
compatible: 兼容
concurrent: 并发
confine: 局限
controversy: 争议
converse: 交谈
device: 设备
devote: 奉献
diminish: 减
distort: 歪曲
duration: 为期
erode: 侵蚀
ethic: 伦理
format: 格式
found: 发现
inherent: 固有
insight: 眼光
integral: 积分
intermediate: 中间
manual: 手册
mature: 成熟
mediate: 调解
medium: 中
military: 军事
minimal: 最小
mutual: 相互
mutually: 相互
norm: 规范
overlap: 交叠
passive: 被动
portion: 一部分
protocol: 协议
qualitative: 定性
refine: 提炼
relax: 放松
restrain: 抑制
revolution: 革命
rigid: 严格
route: 路线
scenario: 脚本
sphere: 球
subordinate: 下属
supplement: 补充
suspend: 暂停
team: 团队
temporary: 临时
trigger: 触发
unify: 统一
violate: 违反
vision: 视力
