module Tests where

import LogicalForm
import Parsing

biz_test = [
	"Adela greeted John Doe.",
	"John Doe visited the company.",
	"Claritza greeted John Doe.",
	"The receptionist greeted the visitor.",
	"The receptionist greeted visitors.",
	"The receptionist greeted customers",
	"The boss greeted visitors.",
	-- "The company's receptionist greeted visitors."
	"The company had customers."
	]


spell_test = [
	"Adela could spell names.",
	"Claritza's niece could spell names.",
	"Claritza could spell names.",
	"Claritza couldn't spell names.",
	"Claritza knew English but Claritza couldn't spell names.",
	"Claritza's boss could spell names.",
	"Claritza couldn't spell John Doe's name.",
	"Adela could spell Claritza's name,\
	\ but Claritza couldn't spell Adela's name.",
	"Joan could spell John Doe's name and John Doe could spell Claritza's name,\
	\ but Claritza couldn't spell Joan's name.",
	"John Doe could spell names.\
	\ Joan could spell names.\
	\ Claritza's niece could spell names.\
	\ But, Claritza couldn't spell names."
	]

test_text = [
	"Claritza's niece spoke English.",
	-- "Claritza's niece's brother spoke English.",
	"Claritza's niece had a brother and a brother spoke English.",
	"Claritza's niece knew English and the boss spoke English.",
	"Claritza's niece spoke English but the boss didn't speak English.",
	"Claritza talked to the boss and the boss talked to Claritza's niece.",
	"Claritza talked to the boss and the boss talked to John Doe \
	\and John Doe talked to Claritza.",
	"Claritza looked back on her niece's upbringing. \
	\Claritza talked to the boss. \
	\Claritza's niece asked the boss about the Dominican Republic."
	]

test_possessives = [
	"Joan's receptionist looked back.",
	"Claritza's niece looked back.",
	"Joan's daughter looked back on Claritza's upbringing.",
	"Joan's daughter looked back on Joan's upbringing.",
	"Claritza's niece looked back on Claritza's upbringing.",
	"Did Claritza's father look back on Claritza's upbringing?",
	"Did Claritza's brother look back on Claritza's upbringing?",
	"Did Claritza's father speak English?",
	"Did Claritza's brother speak English?",
	"Did Claritza's brother know English?",
	"Did Claritza's mother speak English?",
	"Did Claritza's mother speak English?",
	"The boss's daughter appreciated Claritza's father.",
	"Claritza's niece  appreciated the boss's daughter.",
	"Did the sister of Claritza's niece know English?",
	"Did the father of Claritza's niece look back on Claritza's niece's upbringing?",
	"Did the brother of Claritza's niece look back on Claritza's niece's upbringing?",
	"Did the mother of Claritza's niece speak English?",
	"Did the father of Claritza's niece speak English?",
	"Did the brother of Claritza's niece speak English?",
	"Did the mother of Claritza's niece speak English?",
	"Did the brother of Claritza's niece know English?",
	"Did the sister of Claritza's niece know English?"
	]
haves = [
	"Did Claritza have Claritza's father?",
	"Did Claritza have John Doe?",
	"Did Claritza have a mother?",
	"Did Claritza have a niece?",
	"Did Claritza have a daughter?",
	"Did Claritza's father have a mother?",
	"Did Claritza have a job?",
	"Did Claritza have some job?",
	"Did Claritza have money?",
	"Did Claritza's father have money?",
	"Did John Doe have money?",
	"Did Claritza have a parent?",
	"Did Claritza have some parents?",
	"Did Claritza have parents?",
	"Did Claritza's father have a parent?",
	"Did Claritza's father have some parents?",
	"Did Claritza's father have parents?",
	"Did Claritza have work?",
	"Did John Doe work?",
	"Did John Doe have work?",
	"Did John Doe have a job?",
	"Did Claritza's father have work?",
	"Did the boss have the job?",
	"Did the boss have Claritza's niece?",
	"Did the boss have a mother?",
	"Did the boss have a niece?",
	"Did the boss have a daughter?",
	"Did the job have a mother?",
	"Did the boss have receptionists?",
	"Did the boss have some receptionists?",
	-- "Did the boss's daughter have some receptionists?",
	-- "Did the boss's daughter have a receptionist?",
	"Did the daughter have some receptionists?",
	"Did the daughter have no receptionists?",
	-- "Claritza's niece had many receptionists in the Dominican Republic.",
	"Did the parent have some receptionists?",
	"Did the parent have no receptionists?",
	"Did the boss have money?",
	"Did Joan have money?",
	"Did the job have money?",
	"Did Claritza's niece have money?",
	"Did the boss have a parent?",
	"Did the boss have some parents?",
	"Did the boss have parents?",
	"Did the job have a parent?",
	"Did the job have some parents?",
	"Did the job have parents?",
	"Did the boss have a worker?",
	"Did Claritza's niece have a worker?",
	"Did the job have a worker?",
	"Did someone have a worker?"
	]

ungrammatical = [
	"Did John Doe worked?",
	"Claritza work?",
	"Man worked.",
	"Some man work.",
	"No worked.",
	"No-one work.",
	"Did John Doe teach?",
	"John Doe teach Claritza.",
	"Claritza taught.",
	"Did Claritza's niece looked back?",
	"the boss look back?",
	"Man looked back.",
	"Some man work.",
	"No looked back.",
	"No-one work.",
	"Did Claritza's niece teach?",
	"Claritza's niece teach the boss.",
	"the boss raised."
	]

intransitives = [
	"Did John Doe work?",
	"Did Claritza work?",
	"Did Claritza's father work?",
	"A man worked.",
	"Some man worked.",
	"No one worked.",
	"No-one worked.",
	"Everybody worked.",
	"Everyone worked.",
	-- "Many persons worked.",
	"No person worked.",
	"Did the man work?",
	"Did some man work?",
	"Did some men work?",
	"Did some woman work?",
	"Did some women work?",
	"Most women worked.",
	"Most women didn't work.",
	"Several women worked.",
	"Several women didn't work.",
	"Many women worked.",
	"Many women didn't work.",
	"All women worked.",
	"No woman worked.",
	"Most men worked.",
	"Most men didn't work.",
	"Several men worked.",
	"Several men didn't work.",
	"Many men worked.",
	"Many men didn't work.",
	"All men worked.",
	"No man worked.",
	"Did Claritza work at a company?",
	"Did John Doe work at a company?",
	"Did John Doe work at a hospital?",
	"Did Claritza's father work at a company?",
	"Claritza's father worked on a company?",
	"Claritza's father worked in a company?",
	"Claritza's niece got married.",
	"Did Claritza's niece leave?",
	"Did the boss leave?",
	"Did Claritza's father leave?",
	"A man left.",
	"Some man left.",
	"No one left.",
	"No-one left.",
	"Everybody left.",
	"Everyone left.",
	"Many persons left.",
	"No person left.",
	"Did the man leave?",
	"Did some man leave?",
	"Did some men leave?",
	"Did some woman leave?",
	"Did some women leave?",
	"Most persons left.",
	"Most men left.",
	"Most men didn't leave.",
	"Several men left.",
	"Several men didn't leave.",
	"Several persons left.",
	"Several persons didn't leave.",
	"Did Claritza's niece look back?",
	"Did the boss look back?",
	"Did Claritza look back?",
	"A man looked back.",
	"Some man looked back.",
	"No one looked back.",
	"No-one looked back.",
	"Everybody looked back.",
	"Everyone looked back.",
	"Many persons looked back.",
	"No person looked back.",
	"Did the man look back?",
	"Did the girl look back?",
	"Did some man look back?",
	"Did some men look back?",
	"Did some woman look back?",
	"Did some women look back?",
	"Most men looked back.",
	"Most men didn't look back.",
	"Several men looked back.",
	"Several men didn't look back.",
	"Many men looked back.",
	"Many men didn't work.",
	"All men looked back.",
	"No man looked back."
	]

transitives = [
	-- "Did John Doe study?",
	"Did John Doe study IT?",
	"John Doe studied information technology.",
	"Claritza studied information technology.",
	"Claritza studied information technology in the Dominican Republic.",
	"Claritza studied information technology at Boston University",
	"Did Claritza go to Boston University.",
	"Some woman went to Boston University.",
	"Some man went to Boston University.",
	"Some boy went to Boston University.",
	"Some man raised Claritza.",
	"A man raised John Doe",
	"Some woman told a story.",
	"Did the boss work in the Dominican Republic?",
	"Did the boss work in the company?",
	"The boss worked on the company.",
	"The boss worked at the company.",
	"Did the boss work at a hospital?",
	"The boss worked on a hospital.",
	"The boss worked in a hospital.",
	"The boss worked as a receptionist.",
	"Did the job work at a hospital?",
	"The job worked on a hospital.",
	"The job worked in a hospital.",
	"Did the job disappoint the boss?",
	"Did Claritza's niece study information technology?",
	"Claritza's niece studied information technology.",
	"The boss studied information technology.",
	"Did the boss study in the United States?",
	"The boss studied information technology at a hospital.",
	"The boss studied information technology at school",
	"Did the boss go to school.",
	"Some woman went to school.",
	"Some man went to school.",
	"Some boy went to school.",
	"Some man raised the boss.",
	"A man raised Claritza's niece",
	"Some woman told a story.",
	"Did the boss come from the Dominican Republic?",
	"Did Claritza immigrate?",
	"Did the boss immigrate to the United States?",
	"Did Claritza go to the United States?",
	"Did Claritza come from the Dominican Republic?",
	"Did Claritza's niece come to the United States?"
	]

ditransitive_tests = [
	"Claritza told a story.",
	"Claritza told Claritza's father a story.",
	"Claritza told a story to Claritza's niece.",
	"Claritza told a story to John Doe",
	"Claritza gave some job to John Doe.",
	"Did Claritza give some job to John Doe.",
	"Did Claritza give the job to John Doe?",
	"Did Claritza give the job to someone?",
	"Claritza gave several job to John Doe.",
	"Did someone give something to John Doe?",
	"A woman gave the job to John Doe.",
	"A woman gave the job to someone.",
	"A woman gave something to someone.",
	"Someone gave something to someone.",
	"Claritza gave John Doe some job.",
	"Did Claritza give John Doe some job?",
	"Did Claritza give John Doe the job?",
	"Did Claritza give someone the job?",
	"Claritza gave John Doe several job.",
	"Did someone give John Doe something?",
	"A man gave John Doe the job.",
	"A boy gave John Doe the job.",
	"Leroy gave John Doe the shoe.",
	"A man gave someone the job.",
	"A man gave someone something.",
	"Someone gave someone something.",
	"The boss told a story.",
	"The boss told the job a story.",
	"The boss told a story to the job.",
	"The boss told a story to Claritza's niece",
	"The boss gave some receptionists to Claritza's son.",
	"Did the boss give some receptionists to Claritza's son.",
	"Did the boss give the receptionists to Claritza's niece?",
	"Did the boss give the receptionists to someone?",
	"The boss gave several receptionists to Claritza's son.",
	"Did someone give something to Claritza's niece?",
	"A woman gave the receptionists to Claritza's son.",
	"A woman gave the receptionists to someone.",
	"A woman gave something to someone.",
	"Someone gave something to someone.",
	"The boss gave Claritza's niece some receptionists.",
	"Did the boss give Claritza's niece some receptionists?",
	"Did the boss give Claritza's niece the receptionists?",
	"Did the boss give someone the receptionists?",
	"The boss gave Claritza's niece several receptionists.",
	"Did someone give Claritza's niece something?",
	"A man gave Claritza's niece the receptionists.",
	"A man gave Claritza's niece some receptionists.",
	"A boy gave Claritza's niece the receptionists.",
	"The job gave Claritza's niece the worker.",
	"A man gave someone the receptionists.",
	"A man gave someone something.",
	"Someone gave someone something.",
	"Did the boss work at a hospital?",
	"The boss did cleaning at a hospital.",
	"Did Claritza's niece spell names in the company?"
	]

wh_questions =[
	"Who worked?",
	"Who did John Doe teach?",
	"Who taught John Doe?",
	"Who gave the job to John Doe?",
	"Who gave some job to John Doe?",
	"Which person worked?",
	"Which person did John Doe teach?",
	"To whom did Claritza give some job?",
	"Who did Claritza give some job to?",
	"Who looked back?",
	"Which man looked back?",
	"Who raised Claritza's niece?",
	"Which woman raised Claritza's niece?",
	"Who gave the receptionists to Claritza's niece?",
	"Who gave some receptionists to Claritza's niece?",
	"Which person looked back?",
	"Which woman appreciated the boss?",
	"Which girl appreciated the boss?",
	"Which daughter appreciated the boss?",
	"Who did Claritza's niece appreciate?",
	"Which person did Claritza's niece appreciate?",
	"Which man did Claritza's niece appreciate?",
	"Which woman did Claritza's niece appreciate?",
	"Which thing did Claritza's niece appreciate?",
	"Which worker did Claritza's niece appreciate?",
	-- "To whom did the boss give some receptionists?",
	-- "Who did the boss give some receptionists to?",
	"Who had a worker?",
	"What did Claritza's niece have?",
	"Who did Claritza's niece have?",
	"Who did the job disappoint?",
	"Who did the boss's daughter appreciate?",
	"What did the boss's daughter appreciate?",
	"Which thing did the boss's daughter appreciate?",
	"Which man did the boss's daughter appreciate?",
	"Which woman did the boss's daughter appreciate?",
	"Which worker did the boss's daughter appreciate?",
	"What did someone have?"
	]

relclauses = [
	"A woman who taught John Doe worked.",
	"The woman who taught John Doe worked.",
	"Did the woman who taught John Doe work?",
	"Did every woman who taught John Doe work?",
	"The woman who gave the job to John Doe worked.",
	"Claritza divorced the man that she gave the job to.",
	"Who killed the man that helped the woman " 
	 ++ "that had a boyfriend.",
	"A woman who raised Claritza's niece looked back.",
	"The woman who raised Claritza's niece looked back.",
	"Did the woman who raised Claritza's niece look back?",
	"Did every person who raised Claritza's niece look back?",
	"Did some person who raised Claritza's niece look back?",
	"The woman who gave the receptionists to Claritza's niece looked back.",
	"Claritza married the man that gave the receptionists to Claritza's son.",
	"The man that Claritza married gave the receptionists to Claritza's son.",
	"The man Claritza married gave the receptionists to Claritza's son.",
	"The job disappointed the man that gave Claritza's niece the receptionists.",
	"The man that the job disappointed left the Dominican Republic.",
	"The man the job disappointed left the Dominican Republic.",
	"Claritza's niece accepted the receptionists that a man gave Claritza's son.",
	"Claritza's niece accepted the receptionists that a man gave to Claritza's son.",
	"Who appreciated the man that gave the girl \
	 \that left the Dominican Republic a receptionist?"
	]



lf0 = Rel "worked" [ Const(ents!!17) ]
lf00 = (Conj [(Rel "person" [Var 0]), (Rel "worked" [Var 0]) ] ) 
-- lf000 = (Exists (Conj [(Rel "person" [Var 0]), (Rel "worked" [Var 0]) ] )) (Const(ents)!!17)

lf1 = (Equi  (Rel "married" [ Const(ents!!9), Const(ents!!1) ]) (Neg (Rel "married" [ Const(ents!!8), Const(ents!!17)]) ) )

lf2 = (Conj [ (Rel "married" [ Const (ents !! 9), Const       (ents !! 1)]), (Rel "married" [ Const (ents !! 8), Const (ents !!   17)]) ] )

lf3 = Rel "married" [ Const (ents !! 8), Const (ents !! 17)]
lf4 = (Impl  (Rel "married" [ Const (ents !! 9), Const        (ents !! 1)]) (Rel "married" [ Const (ents !! 8), Const (ents !!    17)])  )
lf5 = (Conj [ (Rel "married" [ Const (ents !! 9), Const       (ents !! 1)]), (Rel "married" [ Const (ents !! 8), Const (ents !!   17)]) ] )
lf6 = (Disj [ (Rel "married" [ Const (ents !! 9), Const       (ents !! 1)]), (Rel "married" [ Const (ents !! 8), Const (ents !!   17)]) ] )

lf70 = ( \x -> ( Conj [ (Rel "niece" [x]), (Rel "have" [x, Const (ents !! 8)]) ] ) ) (Const (ents !! 12) )
lf71 = ( \x -> ( Conj [ (Rel "niece" [x]), (Rel "have" [x, Const (ents !! 17)]) ] ) ) (Const (ents !! 12) )
lf72 = ( \x -> ( Conj [ (Rel "niece" [x]), (Rel "have" [x, Const (ents !! 17)]) ] ) ) (Const (ents !! 12) )
lf73 = \x -> Conj [ (Rel "niece" [x]), (Rel "have" [x, Const (ents !! 17)]) ]
lf74 = ( \x -> ( Conj [ (Rel "daughter" [x]), (Rel "have" [x, Const (ents !! 17)]) ] ) )
lf75 = \x -> Impl (Rel "niece" [x]) (Rel "have" [x, Const (ents !! 17)])
