module Tests where

import LogicalForm
import Parsing

all_tests = test_text ++ comp_test1 ++ comp_test2 ++ tag_test ++ neg_tag_test ++
		test_possessives ++ haves ++ intransitives ++ transitives ++ 
		ditransitive_tests ++ relclauses ++ relppR_test
		-- ++ wh_questions ++ comp_wh_questions
		-- ++ ungrammatical

student_tests = [

	]

student_tests_wh = [

	]

test_text = [
	"Barbara's boss talked to Eva.",
	"Barbara's boss had a brother and a brother was black.",
	"Barbara's boss talked to Eva and a co-worker talked to Jennifer.",
	"Barbara's boss talked to Eva but a co-worker didn't talk to Jennifer.",
	"Barbara talked to a co-worker and a co-worker talked to Barbara's boss.",
	"Barbara talked to a co-worker and a co-worker talked to Eva \
	\and Eva talked to Barbara.",
	"Barbara hoped to get the job on a boss's upbringing. \
	\Barbara talked to a co-worker. \
	\Barbara's boss asked a co-worker about Barbara."
	]

comp_test1 = [
	"Barbara was strong.",
	"Barbara was aggressive.",
	"Barbara was a sales representative.",
	"Barbara was Eva's co-worker.",
	"Barbara was a successful woman.",
	"Barbara was a man.",
	"Barbara was a woman.",
	"Barbara was a sales manager",
	"A man was Tadeusz.",
	"A woman was Eva.",
	"The woman was Eva.",
	"Barbara was a black woman.",
	"Barbara was the black woman.",
	"A black woman was Barbara.",
	"A ambitious woman was Barbara.",
	"The ambitious woman was Barbara.",
	"The black woman was Barbara.",
	-- "The successful black woman was Barbara.",
	-- "Barbara was the successful black woman.",
	"Jennifer was the black woman's mother.",
	"Jennifer was the black woman's boss.",
	"Jennifer was a black woman's boss.",
	"Jennifer was an ambitious woman's boss.",
	"Jennifer was an ambitious woman's co-worker.",
	"Dr Bean was the ambitious women's co-worker.",
	"Eva was the ambitious women's co-worker.",
	"Eva was an ambitious woman's co-worker.",
	"Eva was the black woman's co-worker.",
	"Eva was a black woman's co-worker.",
	"Eva was Barbara's co-worker.",
	"Dr Bean was Barbara's co-worker.",
	"Dr Bean was Tadeusz's co-worker.",
	"Jennifer was Barbara's boss.",
	"Jennifer was Eva's boss.",
	"Barbara was Eva's boss.",
	"Barbara was Eva's mother.",
	"Barbara was Jennifer's mother.",
	"Some women were ambitious.",
	"Dr Bean was a co-worker and Eva was a co-worker.",
	"Dr Bean was a woman and Eva was a woman",
	"Some co-workers were women.",
	"Some women were co-workers.",
	"All co-workers were women.",
	"All women were co-workers.",
	"All ambitious women were successful."
	]

comp_test2 = [
	"Some woman was ambitious.",
	"Some women was successful.",
	"Some women were successful.",
	"Eva was a woman.",
	"Was Eva a woman?",
	"Were some women co-workers?",
	"Was Tadeusz's co-worker a woman?",
	"Eva was Dr Bean's co-worker.",
	"Eva was Tadeusz's co-worker.",
	"Eva was Barbara's co-worker.",
	"Barbara was an ambitious woman who was a mother.",
	"Barbara was an ambitious woman who had a boss.",
	"Barbara was an ambitious woman with a boss.",
	"Barbara was an ambitious woman from a boss.",
	"The ambitious woman who had a boss was Barbara.",
	"Barbara had a boss.",
	"Barbara was an ambitious woman.",
	"Barbara was a woman who was ambitious.",
	"Tadeusz was Barbara's boss.",
	"Barbara was Tadeusz's boss.",
	"Tadeusz was Barbara's co-worker."
	]

tag_test = [
	"Barbara worked, didn't she.",
	"Some woman was ambitious, wasn't she.",
	"Some women were successful, wasn't she.",
	"Some women were successful, weren't they.",
	"Eva was a woman with a boss, wasn't she?",
	"Was Eva a woman, wasn't she?",
	"Barbara was an ambitious woman who was a mother, wasn't she?",
	"Barbara was an ambitious woman who had a boss, wasn't she?",
	"The ambitious woman who had a boss was Barbara, wasn't she?",
	"Barbara had a boss, didn't she?",
	"Barbara had a boss, wasn't she?",
	"Barbara had a mother, did she?",
	"Barbara did have a mother, didn't she?",
	"Barbara didn't have a mother, did she?",
	"Barbara didn't have a mother, did he?",
	"Some women had co-workers, didn't they?"
	]

neg_tag_test = [
	"Barbara didn't work, did she.",
	"Some woman wasn't ambitious, was she.",
	"Some women weren't successful, was she.",
	"Some women weren't successful, were they.",
	"Eva wasn't a woman with a boss, was she?",
	"Wasn't Eva a woman, was she?",
	"Barbara wasn't an ambitious woman who was a mother, was she?",
	"Barbara wasn't an ambitious woman who had a boss, was she?",
	"The ambitious woman who had a boss wasn't Barbara, was she?",
	"Barbara didn't have a boss, did she?",
	"Barbara didn't have a boss, was she?",
	"Barbara didn't have a mother, did she?",
	"Barbara did have a mother, didn't she?",
	"Barbara did have a mother, did she?",
	"Barbara did have a mother, did he?",
	"Some women didn't have co-workers, did they?"
	]

test_possessives = [
	"Jennifer's mother hoped to get the job.",
	"Barbara's co-worker talked to the boss.",
	"Barbara's boss got Jennifer's birthday card.",
	"Did Jennifer's mother give a birthday card to the black woman's boss?",
	"Did Jennifer's mother give a birthday card to a black woman's boss?",
	"Did Eva talk to Jennifer?",
	"The boss of Barbara talked to Eva.",
	"Did the co-worker of Barbara talk to Jennifer?",
	"Did a co-worker of Barbara talk to Jennifer?",
	"Did the co-worker of a black woman talk to Barbara's boss?",
	"Did the co-worker of the black woman have money?",
	"Did a co-worker of an ambitious woman have money?",
	"Did the co-workers of the ambitious women have money?",
	"Did the mother of Jennifer have money?",
	"Did the boss of Barbara have money?",
	"Did the boss of the black woman have money?",
	"Did the boss of Barbara talk to Eva?"
	]
haves = [
	-- "The lotion had a beautiful smell",
	"Did Barbara have Jennifer?",
	"Did Barbara have Jennifer's father?",
	"Did Barbara have a husband?",
	"Did Barbara have a mother?",
	"Did Barbara have a boss?",
	"Did Barbara's father have a mother?",
	"Did Eva have a job?",
	"Did Eva have some job?",
	"Did Eva have money?",
	"Did Barbara's father have money?",
	"Did Eva have money?",
	"Did Tadeusz have a parent?",
	"Did Tadeusz have some parents?",
	"Did Tadeusz have parents?",
	"Did Tadeusz's father have a parent?",
	"Did Tadeusz's father have some parents?",
	"Did Tadeusz's father have parents?",
	"Did Tadeusz have work?",
	"Did Eva work?",
	"Did Eva have work?",
	"Did Eva have a job?",
	"Did Barbara have work?",
	"Did Barbara have a job?",
	"Did Barbara's father have work?",
	"Did a co-worker have a job?",
	"Did a co-worker have a woman's job?",
	"Did a co-worker have Barbara's job?",
	"Did a co-worker have a mother?",
	"Did a co-worker have a boss?",
	-- "Did a job have a salary?",
	"Did an ambitious woman have money?",
	"Did an ambitious woman have some money?",
	"Did an ambitious woman's boss have some money?",
	"Did an ambitious woman's boss have a birthday card?",
	"Did the boss have some money?",
	"Did the boss have no money?",
	"Eva's boss had many jobs in the State of Colorado.",
	"Did the parent have some lotion?",
	"Did the parent have no lotion?",
	"Did the State of Colorado have money?",
	"Did the Gathering Place have money?",
	"Did the job have money?",
	"Did Barbara's boss have money?",
	"Did a co-worker have a parent?",
	"Did a co-worker have some parents?",
	"Did a co-worker have parents?",
	"Did the job have a parent?",
	"Did the job have some parents?",
	"Did the job have parents?",
	"Did a co-worker have a worker?",
	"Did Barbara's boss have a worker?",
	"Did the job have a worker?",
	"Did someone have a worker?"
	]

ungrammatical = [
	"Did Eva worked?",
	"Barbara work?",
	"Man worked.",
	"Some man work.",
	"No worked.",
	"No-one work.",
	"Did Eva taught?",
	"Eva teach Barbara.",
	"Barbara taught.",
	"Did Barbara's boss hoped to get the job?",
	"A co-worker look back?",
	"Man hoped to get the job.",
	"Some man work.",
	"No hoped to get the job.",
	"No-one work.",
	"Did Barbara's boss taught?",
	"Barbara's boss teach a co-worker.",
	"A co-worker raised."
	]

intransitives = [
	"Eva worked",
	"Did Eva work?",
	"Barbara's father worked.",
	"A woman's father worked.",
	"Did Barbara's father work?",
	"Did a woman's father work?",
	"A man worked.",
	"Some man worked.",
	"No one worked.",
	"No-one worked.",
	"Everybody worked.",
	"Everyone worked.",
	"Many persons worked.",
	"No person worked.",
	"Did the man work?",
	"Did some man work?",
	"Did some men work?",
	"Did some woman work?",
	"Did some women work?",
	"Most women worked.",
	"Most women didn't work.",
	"Several women worked.",
	"Several women didn't work.",
	"Many women worked.",
	"Many women didn't work.",
	"All women worked.",
	"No woman worked.",
	"Most men worked.",
	"Most men didn't work.",
	"Several men worked.",
	"Several men didn't work.",
	"Many men worked.",
	"Many men didn't work.",
	"All men worked.",
	"No man worked.",
	"Did Barbara work for the State of Colorado?",
	"Did Eva work for the State of Colorado?",
	"Did Eva work at a company?",
	"Did Barbara's father work for the State of Colorado?",
	"Barbara's boss got married.",
	"Did Barbara's boss work?",
	"Did the co-worker work?",
	"Did Barbara's father work?",
	"A man worked.",
	"Some man worked.",
	"No one worked.",
	"No-one worked.",
	"Everybody worked.",
	"Everyone worked.",
	"Many persons worked.",
	"No person worked.",
	"Did the man work?",
	"Did some man work?",
	"Did some men work?",
	"Did some woman work?",
	"Did some women work?",
	"Most persons worked.",
	"Most men worked.",
	"Most men didn't work.",
	"Several men worked.",
	"Several men didn't work.",
	"Several persons worked.",
	"Several persons didn't work.",
	"Did Barbara's boss look back?",
	"Did a co-worker look back?",
	"Did Barbara look back?",
	"A man hoped to get the job.",
	"Some man hoped to get the job.",
	"No one hoped to get the job.",
	"No-one hoped to get the job.",
	"Everybody hoped to get the job.",
	"Everyone hoped to get the job.",
	"Many persons hoped to get the job.",
	"No person hoped to get the job.",
	"Did the man look back?",
	"Did the girl look back?",
	"Did some man look back?",
	"Did some men look back?",
	"Did some woman look back?",
	"Did some women look back?",
	"Most men hoped to get the job.",
	"Most men didn't look back.",
	"Several men hoped to get the job.",
	"Several men didn't look back.",
	"Many men hoped to get the job.",
	"Many men didn't work.",
	"All men hoped to get the job.",
	"No man hoped to get the job."
	]

transitives = [
	"Did Eva study?",
	"Did Eva study IT?",
	"Eva studied counseling.",
	"Barbara studied counseling.",
	"Barbara studied counseling in the State of Colorado.",
	"Barbara studied counseling at the State of Colorado.",
	"Did Barbara go to the State of Colorado?",
	"Some woman went to the State of Colorado.",
	"Some man went to the State of Colorado.",
	"Some boy went to the State of Colorado.",
	"Some man raised Barbara.",
	"A man raised Eva",
	"Some woman told a story.",
	"Did a co-worker work in the the State of Colorado?",
	"Did a co-worker work in the Gathering Place?",
	"A co-worker worked on the Gathering Place.",
	"A co-worker worked at the Gathering Place.",
	"Did a co-worker work at a company?",
	"A co-worker worked on a company.",
	"A co-worker worked in a company.",
	"A co-worker worked as a co-worker.",
	"Did the job work at a company?",
	"The job worked on a company.",
	"The job worked in a company.",
	"Did the job disappoint a co-worker?",
	"Did Barbara's boss study counseling?",
	"Barbara's boss studied counseling.",
	"A co-worker studied counseling.",
	"Did a co-worker study in the State of Colorado?",
	"A co-worker studied counseling at a company.",
	"A co-worker studied counseling at the company.",
	"Did a co-worker go to the company.",
	"Some woman went to the company.",
	"Some man went to the company.",
	"Some boy went to the company.",
	"Some man raised a co-worker.",
	"A man raised Barbara's boss",
	"Some woman told a story.",
	"Did a co-worker come from the State of Colorado?",
	"Did Barbara immigrate?",
	"Did a co-worker immigrate to the State of Colorado?",
	"Did Barbara go to the State of Colorado?",
	"Did Barbara come from the State of Colorado?",
	"Did Barbara's boss come to the State of Colorado?"
	]

ditransitive_tests = [
	"Barbara told a story.",
	"Barbara told Barbara's father a story.",
	"Barbara told a story to Barbara's boss.",
	"Barbara told a story to Eva",
	"Barbara gave some job to Eva.",
	"Did Barbara give some job to Eva.",
	"Did Barbara give the job to Eva?",
	"Did Barbara give the job to someone?",
	"Barbara gave several jobs to Eva.",
	"Did someone give something to Eva?",
	"A woman gave the job to Eva.",
	"A woman gave the job to someone.",
	"A woman gave something to someone.",
	"Someone gave something to someone.",
	"Barbara gave Eva some job.",
	"Did Barbara give Eva some job?",
	"Did Barbara give Eva the job?",
	"Did Barbara give someone the job?",
	"Barbara gave Eva several jobs.",
	"Did someone give Eva something?",
	"A man gave Eva the job.",
	"A boy gave Eva the job.",
	"Dr Bean gave Eva the dress.",
	"A man gave someone the job.",
	"A man gave someone something.",
	"Someone gave someone something.",
	"A co-worker told a story.",
	"A co-worker told the job a story.",
	"A co-worker told a story to the job.",
	"A co-worker told a story to Barbara's boss",
	"A co-worker gave some lotion to Barbara's son.",
	"Did a co-worker give some lotion to Barbara's son.",
	"Did a co-worker give the lotion to Barbara's boss?",
	"Did a co-worker give the lotion to someone?",
	"A co-worker gave a job to Barbara's son.",
	"Did someone give something to Barbara's boss?",
	"A woman gave the lotion to Barbara's son.",
	"A woman gave the lotion to someone.",
	"A woman gave something to someone.",
	"Someone gave something to someone.",
	"A co-worker gave Barbara's boss some birthday_card.",
	"Did a co-worker give Barbara's boss some birthday_card?",
	"Did a co-worker give Barbara's boss the birthday_card?",
	"Did a co-worker give someone the birthday_card?",
	"A co-worker gave Barbara's boss several jobs.",
	"Did someone give Barbara's boss something?",
	"A man gave Barbara's boss the home.",
	"A man gave Barbara's boss some home.",
	"A boy gave Barbara's boss the home.",
	"The job gave Barbara's boss the worker.",
	"A man gave someone the job.",
	"A man gave someone something.",
	"Someone gave someone something.",
	"Did a co-worker work at a company?",
	"A co-worker did work at a company.",
	"Did Barbara's boss give a name to Fast-Track?"
	]

wh_questions =[
	"Who worked?",
	"Who did Eva teach?",
	"Who taught Eva?",
	"Who gave the job to Eva?",
	"Who gave some job to Eva?",
	"Which person worked?",
	"Which person did Eva teach?",
	"What did Dr Bean teach?",
	-- "Who did Barbara give some job?",
	"Who did Barbara give some job to?",
	"Who hoped to get the job?",
	"Which man hoped to get the job?",
	"Who was Barbara's boss?",
	"Who raised Barbara's boss?",
	"Which woman raised Barbara's boss?",
	"Who gave the birthday card to Barbara's boss?",
	"Who gave some birthday card to Barbara's boss?",
	"Who was the ambitious administrative assistant?",
	"Who was the administrative assistant who was ambitious?",
	"Which person hoped to get the job?",
	"Which woman appreciated a co-worker?",
	"Which girl appreciated a co-worker?",
	"Which boss appreciated a co-worker?",
	"Who did Barbara's boss appreciate?",
	"Which person did Barbara's boss appreciate?",
	"Which man did Barbara's boss appreciate?",
	"Which woman did Barbara's boss appreciate?",
	"Which thing did Barbara's boss appreciate?",
	"Which worker did Barbara's boss appreciate?",
	-- "To whom did a co-worker give some languages?",
	-- "Who did a co-worker give some languages to?",
	"Who had a worker?",
	"What did Barbara's boss have?",
	"Who did Barbara's boss have?",
	"Who did the job disappoint?",
	"Who did a co-worker's boss appreciate?",
	"What did a co-worker's boss appreciate?",
	"Which thing did a co-worker's boss appreciate?",
	"Which man did a co-worker's boss appreciate?",
	"Which woman did a co-worker's boss appreciate?",
	"Which worker did a co-worker's boss appreciate?",
	"What did someone have?"
	]

comp_wh_questions = [
	"Who was ambitious?",
	"Who was successful?",
	"Who was a woman?",
	"Who were women?",
	"Who was the woman?",
	"Who was Dr Bean's co-worker?",
	"Who was Tadeusz's co-worker?",
	"Who was Barbara's co-worker?",
	"Who was the ambitious woman that had a boss?",
	"Who was Barbara's boss?",
	"Who was Barbara's boss's mother?"
	]

relclauses = [
	"Barbara was an ambitious woman who was a mother.",
	"Barbara was an ambitious woman who had a boss.",
	"The ambitious woman who had a boss was Barbara.",
	"A woman who taught Eva worked.",
	"The woman who Eva helped worked.",
	"Did the woman who taught Eva work?",
	"Did every woman who taught Eva work?",
	"The woman who gave the job to Eva worked.",
	"Barbara divorced the man that she gave the job to.",
	"Barbara appreciated the man that helped the woman " 
	 ++ "that was ambitious.",
	"A woman who raised Barbara's boss hoped to get the job.",
	"The woman who raised Barbara's boss hoped to get the job.",
	"Did the woman who raised Barbara's boss look back?",
	"Did every person who raised Barbara's boss look back?",
	"Did some person who raised Barbara's boss look back?",
	"The woman who gave the job to Barbara's boss hoped to get the job.",
	"Barbara married the man that gave the job to Barbara's son.",
	"The man that Barbara married gave the job to Barbara's son.",
	"The man Barbara married gave the job to Barbara's son.",
	"The job disappointed the man that gave Barbara's boss the job.",
	"The man that the job disappointed worked for the State of Colorado.",
	"The man the job disappointed worked for the State of Colorado.",
	"Barbara's boss accepted the job that a man gave Barbara's son.",
	"Barbara's boss accepted the job that a man gave to Barbara's son.",
	"Barbara appreciated the man that gave the girl \
	 \that worked for the State of Colorado a job?"
	]



relppR_test = [
	"A woman with some lotion worked.",
	"A woman with no lotion worked.",
	"The woman with the job got a birthday card.",
	"The woman with the job gave a birthday card to Jennifer.",
	"A woman who didn't have a job gave a birthday card to Jennifer.",
	"The woman with the job gave a birthday card."
	]



lf0 = Rel "worked" [ Const(ents!!17) ]
lf00 = (Conj [(Rel "person" [Var 0]), (Rel "worked" [Var 0]) ] ) 
-- lf000 = (Exists (Conj [(Rel "person" [Var 0]), (Rel "worked" [Var 0]) ] )) (Const(ents)!!17)

lf1 = (Equi  (Rel "married" [ Const(ents!!9), Const(ents!!1) ]) (Neg (Rel "married" [ Const(ents!!8), Const(ents!!17)]) ) )

lf2 = (Conj [ (Rel "married" [ Const (ents !! 9), Const       (ents !! 1)]), (Rel "married" [ Const (ents !! 8), Const (ents !!   17)]) ] )

lf3 = Rel "married" [ Const (ents !! 8), Const (ents !! 17)]
lf4 = (Impl  (Rel "married" [ Const (ents !! 9), Const        (ents !! 1)]) (Rel "married" [ Const (ents !! 8), Const (ents !!    17)])  )
lf5 = (Conj [ (Rel "married" [ Const (ents !! 9), Const       (ents !! 1)]), (Rel "married" [ Const (ents !! 8), Const (ents !!   17)]) ] )
lf6 = (Disj [ (Rel "married" [ Const (ents !! 9), Const       (ents !! 1)]), (Rel "married" [ Const (ents !! 8), Const (ents !!   17)]) ] )

lf70 = ( \x -> ( Conj [ (Rel "boss" [x]), (Rel "have" [x, Const (ents !! 8)]) ] ) ) (Const (ents !! 12) )
lf71 = ( \x -> ( Conj [ (Rel "boss" [x]), (Rel "have" [x, Const (ents !! 17)]) ] ) ) (Const (ents !! 12) )
lf72 = ( \x -> ( Conj [ (Rel "boss" [x]), (Rel "have" [x, Const (ents !! 17)]) ] ) ) (Const (ents !! 12) )
lf73 = \x -> Conj [ (Rel "boss" [x]), (Rel "have" [x, Const (ents !! 17)]) ]
lf74 = ( \x -> ( Conj [ (Rel "boss" [x]), (Rel "have" [x, Const (ents !! 17)]) ] ) )
lf75 = \x -> Impl (Rel "boss" [x]) (Rel "have" [x, Const (ents !! 17)])
